# Generated by Django 2.2.10 on 2020-04-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('domain', models.CharField(default='', max_length=50)),
                ('github', models.CharField(default='', max_length=50)),
                ('ports', models.ManyToManyField(related_name='maintainers', to='port.Port')),
            ],
            options={
                'verbose_name': 'Maintainer',
                'verbose_name_plural': 'Maintainers',
                'db_table': 'maintainer',
            },
        ),
        migrations.AddIndex(
            model_name='maintainer',
            index=models.Index(fields=['github'], name='maintainer_github_cc300f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainer',
            index=models.Index(fields=['name', 'domain'], name='maintainer_name_106ce4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maintainer',
            unique_together={('name', 'domain', 'github')},
        ),
    ]
