# Generated by Django 2.1.7 on 2019-04-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_name', models.CharField(db_index=True, max_length=50)),
                ('build_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('port_name', models.CharField(db_index=True, max_length=50)),
                ('time_start', models.CharField(max_length=50)),
                ('time_elapsed', models.CharField(max_length=50)),
                ('build_url', models.URLField(default='')),
                ('watcher_id', models.IntegerField()),
                ('watcher_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.TextField(db_index=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('domain', models.CharField(db_index=True, max_length=50)),
                ('github', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portdir', models.CharField(max_length=100)),
                ('variants', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('homepage', models.URLField(default='')),
                ('epoch', models.TextField(default='')),
                ('platforms', models.TextField(default='')),
                ('long_description', models.TextField(default='')),
                ('version', models.CharField(max_length=100)),
                ('revision', models.IntegerField(default=2)),
                ('closedmaintainer', models.BooleanField()),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('installs_libs', models.BooleanField(default=False)),
                ('replaced_by', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(db_index=True, related_name='category', to='ports.Category')),
            ],
        ),
        migrations.AddField(
            model_name='maintainer',
            name='ports',
            field=models.ManyToManyField(db_index=True, related_name='maintainer_port', to='ports.Port'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='dependencies',
            field=models.ManyToManyField(db_index=True, to='ports.Port'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='port_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_port', to='ports.Port'),
        ),
    ]
