# Generated by Django 2.2.10 on 2020-04-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('domain', models.CharField(default='', max_length=50)),
                ('github', models.CharField(default='', max_length=50)),
                ('ports', models.ManyToManyField(related_name='maintainers', to='port_detail.Port')),
            ],
        ),
        migrations.AddIndex(
            model_name='maintainer',
            index=models.Index(fields=['github'], name='maintainers_github_daaf91_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainer',
            index=models.Index(fields=['name', 'domain'], name='maintainers_name_7df000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maintainer',
            unique_together={('name', 'domain', 'github')},
        ),
    ]
