# Generated by Django 2.2.10 on 2020-05-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(null=True, verbose_name='Result of the last livecheck for the port')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Timestamp when livecheck was last for the port')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livecheck', to='port.Port')),
            ],
            options={
                'verbose_name': 'Livecheck',
                'db_table': 'livecheck',
            },
        ),
        migrations.AddIndex(
            model_name='livecheck',
            index=models.Index(fields=['updated_at'], name='livecheck_updated_9d4b6a_idx'),
        ),
    ]
