# Generated by Django 2.2.10 on 2020-05-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_auto_20200518_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecheck',
            name='error',
            field=models.TextField(null=True, verbose_name='Error thrown by livecheck, defaults to Null if no error encountered'),
        ),
        migrations.AddField(
            model_name='livecheck',
            name='has_updates',
            field=models.BooleanField(default=False, verbose_name='True if updates are available for the port.'),
        ),
        migrations.AlterField(
            model_name='livecheck',
            name='result',
            field=models.TextField(null=True, verbose_name='Result of the last livecheck for the port. Only stored if new version is available'),
        ),
        migrations.AddIndex(
            model_name='livecheck',
            index=models.Index(fields=['has_updates'], name='livecheck_has_upd_c9b429_idx'),
        ),
        migrations.AddIndex(
            model_name='livecheck',
            index=models.Index(fields=['has_updates', 'updated_at'], name='livecheck_has_upd_5f7588_idx'),
        ),
    ]
