# Generated by Django 2.2.10 on 2020-05-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_auto_20200519_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecheck',
            name='port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livecheck', to='port.Port'),
        ),
    ]
