# Generated by Django 2.2.10 on 2020-06-25 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_auto_20200523_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='port',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
