# Generated by Django 2.2.10 on 2020-07-10 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('port', '0005_auto_20200625_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='subscribers',
            field=models.ManyToManyField(related_name='ports', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers of the port'),
        ),
    ]
