# Generated by Django 2.2.10 on 2020-07-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_port_version_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
