# Generated by Django 3.1.12 on 2021-10-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0008_port_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='license',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='port',
            name='portdir',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='port',
            name='replaced_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='version',
            field=models.CharField(default='', max_length=200),
        ),
    ]
