# Generated by Django 2.2.10 on 2020-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
