# Generated by Django 2.2.10 on 2020-08-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_variant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='conflicts',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='requires',
            field=models.TextField(null=True),
        ),
    ]
