# Generated by Django 2.1.7 on 2019-07-15 11:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuildHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('port_name', models.CharField(max_length=100)),
                ('time_start', models.DateTimeField()),
                ('time_elapsed', models.TimeField(null=True)),
                ('watcher_id', models.IntegerField()),
                ('builder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.Builder')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('domain', models.CharField(default='', max_length=50)),
                ('github', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OSDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osx_version', models.CharField(db_index=True, max_length=20)),
                ('month', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portdir', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('homepage', models.URLField(default='')),
                ('epoch', models.BigIntegerField(default=0)),
                ('platforms', models.TextField(null=True)),
                ('long_description', models.TextField(default='')),
                ('version', models.CharField(default='', max_length=100)),
                ('revision', models.IntegerField(default=0)),
                ('closedmaintainer', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('license', models.CharField(default='', max_length=100)),
                ('replaced_by', models.CharField(max_length=100, null=True)),
                ('categories', models.ManyToManyField(db_index=True, related_name='category', to='ports.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PortInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_version', models.CharField(max_length=10)),
                ('xcode_version', models.CharField(max_length=10)),
                ('os_arch', models.CharField(max_length=20)),
                ('macports_version', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('osx_version', models.CharField(max_length=10)),
                ('macports_version', models.CharField(max_length=10)),
                ('xcode_version', models.CharField(max_length=10)),
                ('os_arch', models.CharField(max_length=10)),
                ('full_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(default='', max_length=100)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ports.Port')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.UUID'),
        ),
        migrations.AddField(
            model_name='portinstallation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.Submission'),
        ),
        migrations.AddField(
            model_name='osdistribution',
            name='users',
            field=models.ManyToManyField(related_name='users', to='ports.User'),
        ),
        migrations.AddField(
            model_name='maintainer',
            name='ports',
            field=models.ManyToManyField(related_name='maintainers', to='ports.Port'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='dependencies',
            field=models.ManyToManyField(to='ports.Port'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='port_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_port', to='ports.Port'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['timestamp'], name='ports_submi_timesta_ef1081_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user'], name='ports_submi_user_id_aa7fba_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-timestamp'], name='ports_submi_user_id_e8af69_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'timestamp'], name='ports_submi_user_id_ade7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['os_version'], name='ports_submi_os_vers_0b58c5_idx'),
        ),
        migrations.AddIndex(
            model_name='portinstallation',
            index=models.Index(fields=['submission'], name='ports_porti_submiss_9f52b0_idx'),
        ),
        migrations.AddIndex(
            model_name='portinstallation',
            index=models.Index(fields=['port'], name='ports_porti_port_ff6a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainer',
            index=models.Index(fields=['github'], name='ports_maint_github_4a7ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainer',
            index=models.Index(fields=['name', 'domain'], name='ports_maint_name_edcd1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maintainer',
            unique_together={('name', 'domain', 'github')},
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['port_name'], name='ports_depen_port_na_647c68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('port_name', 'type')},
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name', 'builder_name', '-build_id'], name='ports_build_port_na_f1d25f_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name', 'status', 'builder_name'], name='ports_build_port_na_94f9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name', 'builder_name'], name='ports_build_port_na_3bfa4c_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['-time_start'], name='ports_build_time_st_67b2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name'], name='ports_build_port_na_aea401_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['status'], name='ports_build_status_76abdf_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['builder_name'], name='ports_build_builder_289e95_idx'),
        ),
    ]
