# Generated by Django 2.1.7 on 2019-07-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_add-last-portindex-commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cxx_stdlib',
            field=models.CharField(default='libc++', max_length=20),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['os_arch'], name='ports_submi_os_arch_91ac32_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['macports_version'], name='ports_submi_macport_e2ccfc_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['cxx_stdlib'], name='ports_submi_cxx_std_ba114f_idx'),
        ),
    ]
