# Generated by Django 2.1.7 on 2019-07-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0004_add-fields-to-stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osdistribution',
            name='users',
        ),
        migrations.DeleteModel(
            name='OSDistribution',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
