# Generated by Django 2.1.7 on 2019-08-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0005_remove_models_user_osdist'),
    ]

    operations = [
        migrations.AddField(
            model_name='portinstallation',
            name='variants',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='clt_version',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='portinstallation',
            index=models.Index(fields=['variants'], name='ports_porti_variant_3f6c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['clt_version'], name='ports_submi_clt_ver_e4cece_idx'),
        ),
    ]
