# Generated by Django 2.2.4 on 2019-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0008_alter_field_cxx_stdlib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='time_elapsed',
            field=models.DurationField(null=True),
        ),
    ]
