# Generated by Django 2.2.4 on 2019-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0009_alter_field_time_elapsed_buildhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='display_name',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
    ]
