# Generated by Django 2.2.4 on 2019-10-09 14:19

from django.db import migrations


def add_new_builders(apps, schema_editor):
    Builder = apps.get_model('ports', 'Builder')
    Builder.objects.create(name='10.8_x86_64')
    Builder.objects.create(name='10.7_x86_64')
    Builder.objects.create(name='10.6_x86_64')
    Builder.objects.create(name='10.6_i386')


def populate_display_name_field(apps, schema_editor):
    Builder = apps.get_model('ports', 'Builder')
    for i in Builder.objects.all():
        builder_name = str(i.name)
        display_name = builder_name.replace('_x86_64', '').replace('_legacy', '')
        i.display_name = display_name
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0010_builder_display_name'),
    ]

    operations = [
        migrations.RunPython(add_new_builders),
        migrations.RunPython(populate_display_name_field)
    ]
