# Generated by Django 2.2.10 on 2020-04-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0012_add_10_15_worker'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name', 'builder_name', '-time_start'], name='ports_build_port_na_5f3089_idx'),
        ),
    ]
