# Generated by Django 2.2.10 on 2020-04-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0013_buildhistory_add_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='port_name',
        ),
        migrations.DeleteModel(
            name='LastPortIndexUpdate',
        ),
        migrations.AlterUniqueTogether(
            name='maintainer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='maintainer',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='port',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='port',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Dependency',
        ),
        migrations.DeleteModel(
            name='Maintainer',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
