# Generated by Django 2.2.10 on 2020-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0013_buildhistory_add_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['builder_name', '-time_start'], name='ports_build_builder_2d75ad_idx'),
        ),
    ]
