# Generated by Django 3.1.12 on 2021-10-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portinstallation',
            name='port',
            field=models.CharField(max_length=200),
        ),
    ]
