# Generated by Django 2.2.10 on 2020-05-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildhistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='buildhistory.BuildHistory')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'installed_files',
            },
        ),
    ]
