# Generated by Django 2.2.10 on 2020-05-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildhistory', '0002_installedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='builder_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='buildhistory.Builder'),
        ),
    ]
