# Generated by Django 2.2.10 on 2020-06-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildhistory', '0004_auto_20200605_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='natural_name',
            field=models.CharField(default='', max_length=50, verbose_name='Name of the MacOS version, e.g. Catalina'),
        ),
    ]
