# Generated by Django 3.0.9 on 2020-08-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildhistory', '0006_tempbuildjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildhistory',
            name='port_revision',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buildhistory',
            name='port_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
