# Generated by Django 3.1.12 on 2021-10-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildhistory', '0007_auto_20200806_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='port_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='buildhistory',
            name='port_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
