# Generated by Django 2.2.10 on 2020-04-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPortIndexUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_commit_hash', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portdir', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('homepage', models.URLField(default='')),
                ('epoch', models.BigIntegerField(default=0)),
                ('platforms', models.TextField(null=True)),
                ('long_description', models.TextField(default='')),
                ('version', models.CharField(default='', max_length=100)),
                ('revision', models.IntegerField(default=0)),
                ('closedmaintainer', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('license', models.CharField(default='', max_length=100)),
                ('replaced_by', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(db_index=True, related_name='category', to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('dependencies', models.ManyToManyField(to='port_detail.Port')),
                ('port_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_port', to='port_detail.Port')),
            ],
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['port_name'], name='port_detail_port_na_6882d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('port_name', 'type')},
        ),
    ]
