name: Publish Docker image

# This workflow currently publishes to the following account unless we have an
# official MacPorts repo on DockerHub
#
# DockerHub Repo: arjunsalyan/macports-webapp
# Email: arjun@macports.org
# Github: @arjunsalyan

on:
  push:
    branches: [ main ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ARJUNSALYAN_DOCKER_USERNAME }}
          password: ${{ secrets.ARJUNSALYAN_DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: arjunsalyan/macports-webapp:latest
